/* Lobby, two-player transport, Web Audio effects and mobile controls. */
(()=>{'use strict';const $=id=>document.getElementById(id);
const safeStore={get(k){try{return localStorage.getItem(k);}catch{return null;}},set(k,v){try{localStorage.setItem(k,v);}catch{}}};
let ctx=null,master=null,hum=null,humGain=null,enabled=safeStore.get('el-sound')!=='off',volume=.22;
function unlock(){if(!enabled)return;try{if(!ctx){ctx=new(window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=volume;master.connect(ctx.destination);}if(ctx.state==='suspended')ctx.resume().catch(()=>{});}catch{}}
function tone(freq,duration=.08,type='sine',gain=.25,delay=0,endFreq=null){if(!ctx||ctx.state!=='running'||!enabled)return;const at=ctx.currentTime+delay,osc=ctx.createOscillator(),g=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,at);if(endFreq)osc.frequency.exponentialRampToValueAtTime(endFreq,at+duration);g.gain.setValueAtTime(.001,at);g.gain.exponentialRampToValueAtTime(gain,at+.008);g.gain.exponentialRampToValueAtTime(.001,at+duration);osc.connect(g);g.connect(master);osc.start(at);osc.stop(at+duration+.02);}
function noise(duration=.08,gain=.15){if(!ctx||ctx.state!=='running'||!enabled)return;const count=Math.ceil(ctx.sampleRate*duration),buffer=ctx.createBuffer(1,count,ctx.sampleRate),a=buffer.getChannelData(0);let low=0;for(let i=0;i<count;i++){low=.8*low+.2*(Math.random()*2-1);a[i]=low*(1-i/count);}const src=ctx.createBufferSource(),g=ctx.createGain();src.buffer=buffer;g.gain.value=gain;src.connect(g);g.connect(master);src.start();}
const Sound=window.LabSound={unlock,play(kind){if(!enabled)return;switch(kind){case 'step':noise(.065,.26);tone(95,.04,'sine',.1);break;case 'pickup':tone(440,.07,'triangle',.22);tone(660,.08,'sine',.18,.06);break;case 'place':noise(.06,.25);tone(180,.09,'triangle',.23);break;case 'connect':tone(820,.06,'sine',.2);tone(1200,.06,'sine',.15,.045);break;case 'power':case 'switch':noise(.025,.3);tone(310,.05,'square',.08);break;case 'ready':tone(520,.1,'sine',.2);break;case 'door':case 'win':case 'success':[523,659,784,1046].forEach((f,i)=>tone(f,.32,'sine',.23,i*.1));noise(.35,.12);break;case 'error':tone(180,.15,'triangle',.2);tone(130,.14,'triangle',.15,.13);break;default:noise(.035,.15);}},power(on){if(!ctx||!enabled)return;if(!hum){hum=ctx.createOscillator();hum.frequency.value=60;humGain=ctx.createGain();humGain.gain.value=0;hum.connect(humGain);humGain.connect(master);hum.start();}humGain.gain.setTargetAtTime(on?.018:0,ctx.currentTime,.15);},toggle(){enabled=!enabled;safeStore.set('el-sound',enabled?'on':'off');if(enabled)unlock();if(master)master.gain.value=enabled?volume:0;$('soundBtn').textContent=enabled?'🔊 Дыбыс':'🔇 Дыбыс';},volume(v){volume=v;if(master)master.gain.value=enabled?volume:0;}};
document.addEventListener('pointerdown',unlock,{passive:true});document.addEventListener('keydown',unlock,{passive:true});$('soundBtn').onclick=()=>Sound.toggle();$('soundBtn').textContent=enabled?'🔊 Дыбыс':'🔇 Дыбыс';$('soundVolume').oninput=e=>Sound.volume(+e.target.value);
const input=window.LabInput={x:0,y:0};let joyId=null;const joy=$('joystick'),stick=$('joyStick');function joyMove(e){const r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.32,len=Math.hypot(dx,dy),scale=len>max?max/len:1;input.x=Math.abs(dx*scale/max)<.12?0:dx*scale/max;input.y=Math.abs(dy*scale/max)<.12?0:dy*scale/max;stick.style.transform=`translate(${dx*scale}px,${dy*scale}px)`;}
joy.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();joyId=e.pointerId;joy.setPointerCapture(e.pointerId);window.ElectricLab?.cancelWalk();joyMove(e);});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)joyMove(e);});function joyEnd(e){if(e&&e.pointerId!==joyId)return;joyId=null;input.x=input.y=0;stick.style.transform='translate(0px,0px)';}['pointerup','pointercancel','lostpointercapture'].forEach(ev=>joy.addEventListener(ev,joyEnd));window.addEventListener('blur',()=>joyEnd());document.addEventListener('visibilitychange',()=>{if(document.hidden)joyEnd();});
$('mobileJournal').onclick=()=>$('journalBtn').click();$('analysisBtn').onclick=()=>document.body.classList.toggle('analysisOpen');$('analysisClose').onclick=()=>document.body.classList.remove('analysisOpen');$('toolsBtn').onclick=()=>document.body.classList.toggle('toolsOpen');$('mobileUse').onclick=()=>window.ElectricLab?.interact();$('mobileTake').onclick=()=>window.ElectricLab?.takeAim();$('mobileWire').onclick=()=>window.ElectricLab?.setTool('wire');$('mobileBench').onclick=()=>window.ElectricLab?.bench();$('mobilePower').onclick=()=>$('powerBtn').click();$('mobileSwitch').onclick=()=>$('switchBtn').click();$('morePick').onchange=e=>{if(e.target.value){window.ElectricLab?.pickup(e.target.value);e.target.value='';}};
let hooks={},pendingState=null,source=null,room=null,token=null,myId=null,current=null,hostSession=null,lobbyTimer=null,serial=0,requestPrefix=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),lastSeq=-1,lastEpoch=0,poseInFlight=false,lastPoseSent=0,latestPose=null,queue=Promise.resolve(),seenGoal=false;
const net=window.Coop={active:false,connected:false,get state(){return current;},get playerId(){return myId;},attach(h){hooks=h;if(pendingState)apply(pendingState);},refresh:renderStatus,send(type,data={}){if(!net.active)return false;const epoch=current?.epoch;queue=queue.catch(()=>{}).then(async()=>{if(!net.connected)throw Error('Серіктеспен байланыс қалпына келгенше күтіңіз.');await flushPose(true);const r=await api('/api/action',{room,type,data,epoch,requestId:requestPrefix+'-'+(++serial)},token);if(r.state)apply(r.state);}).catch(e=>{hooks.toast?.(e.message);Sound.play('error');resync();});return true;},pose(p){latestPose=p;flushPose(false);},ready(){net.send('ready');}};
async function api(url,data,auth){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),5000);try{const r=await fetch(url,{method:data?'POST':'GET',headers:{...(data?{'Content-Type':'application/json'}:{}),...(auth?{Authorization:'Bearer '+auth}:{})},body:data?JSON.stringify(data):undefined,signal:ac.signal});const value=await r.json();if(!r.ok){const e=new Error(value.error||'Қосылу қатесі.');e.code=value.code;throw e;}return value;}finally{clearTimeout(timer);}}
async function resync(){if(!net.active)return;try{const s=await api('/api/state?room='+encodeURIComponent(room),null,token);apply(s);}catch{}}
async function flushPose(force){if(!net.active||!net.connected||!latestPose||poseInFlight)return;if(!force&&performance.now()-lastPoseSent<110)return;poseInFlight=true;lastPoseSent=performance.now();try{await api('/api/action',{room,epoch:current.epoch,type:'pose',data:latestPose},token);}catch(e){if(net.connected){try{const s=await api('/api/state?room='+room,null,token);const me=s.players.find(p=>p.id===myId);if(me)hooks.correct?.(me.pos);apply(s);}catch{}}}finally{poseInFlight=false;}}
function apply(s){if(!hooks.apply){pendingState=s;return;}if(current&&s.epoch===current.epoch&&s.revision<current.revision)return;const newRoom=s.epoch!==lastEpoch;if(newRoom){latestPose=null;lastPoseSent=0;}current=s;pendingState=null;hooks.apply(s,myId,newRoom);lastEpoch=s.epoch;if(s.event?.seq>lastSeq){if(lastSeq>=0)Sound.play(s.event.kind);lastSeq=s.event.seq;}Sound.power(s.powered&&!hooks.short?.());if(s.goal.ok&&!seenGoal){Sound.play('success');hooks.toast?.('Тапсырма орындалды! Жасыл есікке екеуің бірге барыңдар.');}seenGoal=s.goal.ok;renderStatus();if(s.finished){$('victory').hidden=false;$('victoryText').textContent='Үш бөлменің тапсырмасын бірге орындадыңдар! Өлшеулерді журналдан жүктей аласыздар.';}}
function renderStatus(){if(!net.active||!current)return;const me=current.players.find(p=>p.id===myId),other=current.players.find(p=>p.id!==myId);$('networkState').textContent=net.connected?(other?.present?'2 / 2 · Бірге ойнап жатыр':'1 / 2 · Серіктесті күту'):'Қайта қосылуда…';$('networkState').classList.toggle('online',net.connected&&!!other?.present);$('identity').textContent=me?.name||'';$('stageLabel').textContent=current.goal.title;$('missionTitle').textContent=current.goal.title;$('missionText').textContent=current.goal.text;$('coopGoal').textContent=current.finished?'Миссия аяқталды!':current.goal.ok?'Тізбек дұрыс. Есік ашық — екеуің бірге барыңдар.':!current.goal.electrical?'Тапсырмадағы тізбекті құрастырыңдар.':'Екінші ойыншы да құрал қойсын немесе сым жалғасын.';
$('contributors').textContent=current.players.map(p=>(current.goal.contributors.includes(p.id)?'✓ ':'○ ')+p.name).join('  ·  ');$('gateBtn').disabled=!current.goal.ok||current.finished;$('gateBtn').textContent=me?.ready?'Серіктесті күту…':'Есікке бару →';$('presetBtn').disabled=true;$('presetBtn').title='Бірлескен миссияда тізбекті өздерің құрастырыңдар.';document.querySelectorAll('[data-pick]').forEach(b=>{const c=current.parts.find(c=>c.id===b.dataset.pick);b.disabled=!!c?.carrier&&c.carrier!==myId;});}
function connectEvents(){source?.close();source=new EventSource('/api/events?room='+encodeURIComponent(room)+'&token='+encodeURIComponent(token));source.addEventListener('state',e=>{net.connected=true;apply(JSON.parse(e.data));});source.addEventListener('poses',e=>{const p=JSON.parse(e.data);if(current&&p.epoch===current.epoch){current.players=p.players;hooks.peers?.(p.players,myId);renderStatus();}});source.onerror=()=>{net.connected=false;renderStatus();};source.addEventListener('expired',()=>{source.close();net.connected=false;showLobbyError('Сессияның екі сағаттық уақыты аяқталды. Жаңа QR жасаңыз.');});source.addEventListener('replaced',()=>{source.close();net.connected=false;showLobbyError('Бұл ойыншы орны басқа бетте ашылды. Ойынды бір бетте пайдаланыңыз.');});}
function showLobbyError(message){$('lobby').hidden=false;$('joinError').textContent=message;$('joinError').hidden=false;$('joinPanel').hidden=false;$('hostPanel').hidden=true;$('joining').textContent='Қосылу тоқтатылды';}
async function joinRoom(id){room=id;$('practiceBtn').hidden=true;$('joinError').hidden=true;$('hostPanel').hidden=true;$('joinPanel').hidden=false;$('joining').textContent='Бөлмеге қосылу…';try{const old=safeStore.get('el-seat-'+id),r=await api('/api/join',{room:id,token:old});token=r.token;myId=r.playerId;safeStore.set('el-seat-'+id,token);net.active=true;net.connected=false;document.body.classList.add('cooperative');apply(r.state);connectEvents();$('lobby').hidden=true;$('identity').textContent=r.playerId==='p1'?'Ойыншы 1':'Ойыншы 2';Sound.unlock();}catch(e){showLobbyError(e.message);}}
async function createRoom(){$('createRoom').disabled=true;$('hostError').textContent='';try{const r=await api('/api/rooms',{base:$('serverAddress').value});hostSession=r;$('qrArea').hidden=false;$('qrImage').src=r.qr;$('joinLink').value=r.joinURL;$('qrCaption').textContent='Осы QR екі ойыншыға арналған · 2 сағат';$('joinHere').hidden=false;clearInterval(lobbyTimer);lobbyTimer=setInterval(async()=>{try{const s=await api('/api/lobby?room='+r.room+'&host='+r.hostToken);$('seatCount').textContent=s.players.length+' / 2 орын алынды';$('hostPlayers').textContent=s.players.map(p=>p.name+(p.present?' · қосылды':' · орны сақталған')).join('   |   ')||'Екі телефонның қосылуын күтіп тұр…';}catch{clearInterval(lobbyTimer);}},1700);}catch(e){$('hostError').textContent=e.message;}finally{$('createRoom').disabled=false;}}
$('createRoom').onclick=createRoom;$('joinHere').onclick=()=>{if(hostSession){history.replaceState(null,'','?room='+hostSession.room);joinRoom(hostSession.room);}};$('practiceBtn').onclick=()=>{$('lobby').hidden=true;Sound.unlock();hooks.toast?.('Жаттығу режимі: дыбыс пен джойстик қосулы. Бірлескен миссияға QR арқылы кіріңіз.');};$('lobbyBtn').onclick=()=>{hooks.release?.();if(net.active){$('joinPanel').hidden=true;$('hostPanel').hidden=false;$('createRoom').hidden=true;$('serverAddress').hidden=true;$('hostHint').textContent='Осы сессияда тек екі ойыншы орны бар. Қайта кіру үшін бастапқы браузерді пайдаланыңыз.';$('qrArea').hidden=false;$('qrImage').src='/api/qr?room='+encodeURIComponent(room);$('joinLink').value=location.origin+'/?room='+room;$('qrCaption').textContent='Ортақ сессия · 2 ойыншы';$('joinHere').hidden=true;$('seatCount').textContent=(current?.players.length||0)+' / 2 орын алынды';}$('lobby').hidden=false;};$('lobbyClose').onclick=()=>{$('lobby').hidden=true;};$('victoryClose').onclick=()=>$('victory').hidden=true;$('gateBtn').onclick=()=>window.ElectricLab?.gate();
async function boot(){const invite=new URLSearchParams(location.search).get('room');if(invite){$('practiceBtn').hidden=true;await joinRoom(invite);return;}$('joinPanel').hidden=true;if(location.protocol==='file:'){$('createRoom').disabled=true;$('serverAddress').disabled=true;$('hostError').textContent='Екі телефонмен ойнау үшін толық жинақтағы Start_Windows.bat файлын іске қосыңыз. Бұл файлдан жеке жаттығуды ашуға болады.';return;}try{const info=await api('/api/info');const choices=info.publicURL?[info.publicURL]:[...new Set([...(info.lan||[]),location.origin])];$('serverAddress').innerHTML='';for(const value of choices){const o=document.createElement('option');o.value=value;o.textContent=value;$('serverAddress').append(o);}$('hostHint').textContent='Компьютер және екі телефон бір Wi-Fi желісінде болсын. Компьютердің Wi-Fi мекенжайын таңдап, QR жасаңыз.';}catch{$('createRoom').disabled=true;$('hostError').textContent='Ортақ ойын сервері табылмады. Толық жинақты іске қосыңыз немесе жеке жаттығуды таңдаңыз.';}}
boot();
})();
