/* Электр Lab: first-person WebGL, procedural room and hands, no CDN or assets.
   Coordinates in metres; y is up. Circuit topology is independent of layout. */
(()=>{'use strict';
const net=window.Coop,sound=window.LabSound;let peers=[],doorOpen=0,lastFootstep=0;
const $=id=>document.getElementById(id), canvas=$('world'), stage=$('stage');
const V={add:(a,b)=>a.map((x,i)=>x+b[i]),sub:(a,b)=>a.map((x,i)=>x-b[i]),mul:(a,s)=>a.map(x=>x*s),dot:(a,b)=>a.reduce((v,x,i)=>v+x*b[i],0),cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],len:a=>Math.hypot(...a),norm(a){return this.mul(a,1/(this.len(a)||1));}};
const mixColor=(a,b,t)=>{t=Math.min(1,Math.max(0,t));return [16,8,0].reduce((r,k)=>r|(Math.round((a>>k&255)*(1-t)+(b>>k&255)*t)<<k),0);};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),fmt=(n,d=2)=>Number.isFinite(n)?n.toFixed(d).replace('.',','):'∞';
const mulMat=(a,b)=>{const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;};
const perspective=(f,a,n,z)=>{const t=1/Math.tan(f/2);return new Float32Array([t/a,0,0,0,0,t,0,0,0,0,(z+n)/(n-z),-1,0,0,2*z*n/(n-z),0]);};
function lookAt(eye,target){const z=V.norm(V.sub(eye,target)),x=V.norm(V.cross([0,1,0],z)),y=V.cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-V.dot(x,eye),-V.dot(y,eye),-V.dot(z,eye),1]);}
function model(pos,s=[1,1,1],a=0){const c=Math.cos(a),q=Math.sin(a);return new Float32Array([c*s[0],0,-q*s[0],0,0,s[1],0,0,q*s[2],0,c*s[2],0,...pos,1]);}
const colorCache={};function color(hex){if(!colorCache[hex])colorCache[hex]=[(hex>>16&255)/255,(hex>>8&255)/255,(hex&255)/255];return colorCache[hex];}
let gl;try{gl=canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:true});}catch(e){}
if(!gl){$('fatal').hidden=false;return;}
const VS=`attribute vec3 aPos;attribute vec3 aNormal;uniform mat4 uModel,uVP;uniform mat3 uNormal;varying vec3 vPos,vNormal;void main(){vec4 w=uModel*vec4(aPos,1.0);vPos=w.xyz;vNormal=normalize(uNormal*aNormal);gl_Position=uVP*w;}`;
const FS=`precision mediump float;varying vec3 vPos,vNormal;uniform vec4 uColor;uniform float uEmit;uniform vec3 uEye;uniform vec3 uLamps[3];uniform vec3 uGlow;void main(){vec3 N=normalize(vNormal),L=normalize(vec3(-0.5,1.0,0.7)),E=normalize(uEye-vPos);float d=max(dot(N,L),0.0);float hemi=0.48+0.18*(N.y*0.5+0.5);float spec=pow(max(dot(N,normalize(L+E)),0.0),42.0)*0.22;vec3 c=uColor.rgb*(hemi+d*0.54)+spec;for(int i=0;i<3;i++){vec3 toL=uLamps[i]-vPos;float dist=length(toL);float glow=i==0?uGlow.x:(i==1?uGlow.y:uGlow.z);c+=uColor.rgb*vec3(1.0,0.72,0.32)*max(dot(N,normalize(toL)),0.0)*glow/(1.0+dist*dist*2.0);}c=mix(c,uColor.rgb,uEmit);float fog=smoothstep(14.0,30.0,length(uEye-vPos));c=mix(c,vec3(0.63,0.75,0.77),fog*0.45);gl_FragColor=vec4(c,uColor.a);}`;
function shader(type,src){const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));return sh;}
let prog;try{prog=gl.createProgram();gl.attachShader(prog,shader(gl.VERTEX_SHADER,VS));gl.attachShader(prog,shader(gl.FRAGMENT_SHADER,FS));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(prog));}catch(e){$('fatal').hidden=false;$('fatalText').textContent='Графика іске қосылмады. WebGL қолдайтын браузерде графикалық үдетуді қосып көріңіз.';console.error(e);return;}
gl.useProgram(prog);const U={};['Model','VP','Normal','Color','Emit','Eye','Lamps[0]','Glow'].forEach(s=>U[s]=gl.getUniformLocation(prog,'u'+s));const aP=gl.getAttribLocation(prog,'aPos'),aN=gl.getAttribLocation(prog,'aNormal');gl.enableVertexAttribArray(aP);gl.enableVertexAttribArray(aN);gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);
function makeMesh(vertices){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);return {b,n:vertices.length/6};}
function triangle(a,b,c,na,nb=na,nc=na){return [...a,...na,...b,...nb,...c,...nc];}
const cubeData=[];for(const [n,ps] of [ [[0,0,1],[[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]]],[[0,0,-1],[[.5,-.5,-.5],[-.5,-.5,-.5],[-.5,.5,-.5],[.5,.5,-.5]]],[[1,0,0],[[.5,-.5,.5],[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5]]],[[-1,0,0],[[-.5,-.5,-.5],[-.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5]]],[[0,1,0],[[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5],[-.5,.5,-.5]]],[[0,-1,0],[[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5],[-.5,-.5,.5]]]])cubeData.push(...triangle(ps[0],ps[1],ps[2],n),...triangle(ps[0],ps[2],ps[3],n));
const sphereData=[];function sp(a,b){return [Math.sin(a)*Math.cos(b),Math.cos(a),Math.sin(a)*Math.sin(b)];}for(let i=0;i<14;i++)for(let j=0;j<24;j++){const a=sp(i*Math.PI/14,j*Math.PI/12),b=sp((i+1)*Math.PI/14,j*Math.PI/12),c=sp((i+1)*Math.PI/14,(j+1)*Math.PI/12),d=sp(i*Math.PI/14,(j+1)*Math.PI/12);sphereData.push(...triangle(a,b,c,a,b,c),...triangle(a,c,d,a,c,d));}
const cylData=[];for(let i=0;i<20;i++){const t=i*Math.PI/10,s=(i+1)*Math.PI/10,n=[Math.cos(t),0,Math.sin(t)],m=[Math.cos(s),0,Math.sin(s)],a=[n[0],-.5,n[2]],b=[m[0],-.5,m[2]],c=[m[0],.5,m[2]],d=[n[0],.5,n[2]];cylData.push(...triangle(a,b,c,n,m,m),...triangle(a,c,d,n,m,n),...triangle([0,.5,0],d,c,[0,1,0]),...triangle([0,-.5,0],b,a,[0,-1,0]));}
const meshes={box:makeMesh(cubeData),sphere:makeMesh(sphereData),cyl:makeMesh(cylData)};
let transparent=[],frameObjects=[];const statics=[];let collecting=null;
function shape(mesh,pos,scale,hex,angle=0,emit=0,alpha=1){const o={mesh,m:model(pos,scale,angle),hex,emit,alpha,pos};(collecting||frameObjects).push(o);return o;}
const box=(p,s,c,a=0,e=0)=>shape('box',p,s,c,a,e),sphere=(p,s,c,e=0,alpha=1)=>shape('sphere',p,s,c,0,e,alpha),cyl=(p,s,c,e=0)=>shape('cyl',p,s,c,0,e);
function segment(a,b,r,c,e=0){const d=V.sub(b,a),l=V.len(d);if(l<1e-6)return;const y=V.mul(d,1/l),x=V.norm(V.cross(Math.abs(y[2])>.95?[1,0,0]:[0,0,1],y)),z=V.cross(x,y),p=V.mul(V.add(a,b),.5);(collecting||frameObjects).push({mesh:'cyl',m:new Float32Array([...V.mul(x,r),0,...V.mul(y,l),0,...V.mul(z,r),0,...p,1]),hex:c,emit:e,alpha:1,pos:p});}
function ring(p,r,c){for(let i=0;i<32;i++){let t=i*Math.PI/16,s=(i+1)*Math.PI/16;segment([p[0]+r*Math.cos(t),p[1],p[2]+r*Math.sin(t)],[p[0]+r*Math.cos(s),p[1],p[2]+r*Math.sin(s)],.016,c,.8);}}
function draw(o){const mesh=meshes[o.mesh],m=o.m,n=new Float32Array(9);for(let c=0;c<3;c++){const sq=m[c*4]**2+m[c*4+1]**2+m[c*4+2]**2||1;for(let r=0;r<3;r++)n[c*3+r]=m[c*4+r]/sq;}gl.bindBuffer(gl.ARRAY_BUFFER,mesh.b);gl.vertexAttribPointer(aP,3,gl.FLOAT,false,24,0);gl.vertexAttribPointer(aN,3,gl.FLOAT,false,24,12);gl.uniformMatrix4fv(U.Model,false,m);gl.uniformMatrix3fv(U.Normal,false,n);gl.uniform4fv(U.Color,[...color(o.hex),o.alpha]);gl.uniform1f(U.Emit,o.emit);gl.drawArrays(gl.TRIANGLES,0,mesh.n);}
function furniture(){collecting=statics;
box([0,-.16,0],[24,.25,22],0xa9c0c0);for(let x=-10.5;x<=10.5;x+=1.5)for(let z=-9.5;z<10.6;z+=1.5)box([x,-.02,z],[1.475,.025,1.475],(Math.round((x+6)/1.5)+Math.round((z+5.5)/1.5))%2?0xc3d3d0:0xb8ccc9);
box([0,2.45,-10],[24,5,.18],0xd2dfda);box([-12,2.45,0],[.18,5,22],0xd8e5df);box([0,.24,-9.88],[24,.4,.12],0x5d8b8c);box([-11.85,.24,0],[.12,.4,21],0x5d8b8c);
// Window panels and architectural light strips.
for(let x=-4.8;x<-.3;x+=1.5){box([x,3.05,-9.87],[1.35,2.28,.05],0x9bc6d0);box([x,3.05,-9.83],[.035,2.28,.05],0xf0f4ed);box([x,3.05,-9.82],[1.35,.035,.05],0xf0f4ed);}box([-3.3,4.26,-9.8],[4.6,.12,.22],0xf5f3e4);box([-3.3,1.88,-9.75],[4.6,.12,.35],0xe8eddf);
box([2.5,3.1,-9.84],[4.65,2.3,.13],0x42686e);box([2.5,3.1,-9.75],[4.43,2.08,.09],0x163d4a);box([2.5,4.14,-9.65],[4.4,.025,.02],0x75f2cb,0,.8);
// Board diagram is decorative: separate complete series and parallel symbols.
for(let i=0;i<3;i++){box([1.05+i,2.55,-9.64],[.42,.25+i*.3,.04],0x5ed8c4,0,.6);}box([2.08,2.32,-9.63],[3.1,.025,.035],0x9fbcb8);
// Back cabinetry and safe low-voltage equipment.
box([.4,.65,-8.72],[10.8,1.3,1.1],0x537f80);box([.4,1.36,-8.72],[11.1,.12,1.25],0xe6e9dc);for(let x=-4.45;x<5.8;x+=1.5){box([x,.65,-8.145],[1.42,1.14,.04],0x709493);box([x,1.05,-8.09],[.4,.055,.04],0xc1d4c9);}
box([-3.6,1.65,-8.7],[1.1,.5,.65],0x243f49);box([-3.6,1.68,-8.34],[.82,.25,.02],0x5db9b4,0,.45);for(let x=-2;x<.5;x+=.33){box([x,1.64,-8.7],[.21,.5,.55],x<-.9?0xa1a09b:0xb8785c);}
// Primary workbench.
box([0,1.42,-.25],[7.45,.22,3.8],0x345964);box([0,1.56,-.25],[7.5,.075,3.85],0xe2e2ca);box([0,1.606,-.25],[6.8,.018,3.2],0x6d9a99);box([0,1.05,1.52],[7,.35,.14],0x214c58);
for(const x of [-3.25,3.25])for(const z of [-1.66,1.15]){box([x,.67,z],[.13,1.35,.13],0x426270);box([x,.04,z],[.24,.07,.24],0x1d3f4c);}box([0,.31,-1.65],[6.55,.11,.1],0x466470);
// Equipment shelf / second table, reachable through the aisle.
box([5.5,1.38,-.4],[1.48,.14,4.6],0x345965);box([5.5,1.48,-.4],[1.5,.06,4.65],0xdecfae);for(let z of [-2.4,1.5])for(let x of [4.9,6.1])box([x,.69,z],[.08,1.38,.08],0x4a6a72);
// Room plant, storage and a stool.
cyl([-5.5,.32,-3.2],[.36,.58,.36],0xc9b69a);for(let i=0;i<8;i++){const a=i*2.4;segment([-5.5,.6,-3.2],[-5.5+.3*Math.cos(a),1.35+i*.06,-3.2+.3*Math.sin(a)],.035,0x426f5b);sphere([-5.5+.33*Math.cos(a),1.25+i*.07,-3.2+.33*Math.sin(a)],[.24,.3,.09],0x5d9374);}
// A complete room surrounds the player in first-person view.
box([12,2.45,.3],[.18,5,22],0xc9dad6);box([-6.8,2.45,11],[10.4,5,.18],0xd4dfd7);box([6.8,2.45,11],[10.4,5,.18],0xd4dfd7);box([0,4.15,11],[3.2,1.7,.18],0xd4dfd7);box([0,1.6,12.25],[3.1,3.2,2.1],0x102834);box([0,5.05,.3],[24,.14,22],0xdbe6df);

for(const x of [-8,-3,2.2,7.5]){box([x,4.94,-.4],[2.8,.045,.48],0x547478);box([x,4.9,-.4],[2.6,.035,.36],0xf3f6df,0,1);}
box([11.86,3.0,-1.6],[.06,1.5,2.4],0x577e82);box([11.81,3.0,-1.6],[.02,1.32,2.22],0x183f4e);
// Left instrument station and distant storage benches.
box([-8.5,1.4,-.9],[1.6,.2,6.4],0x355867);box([-8.5,1.52,-.9],[1.7,.05,6.5],0xdad4b8);for(const z of [-3.7,1.7])for(const x of [-9.1,-7.9])box([x,.7,z],[.1,1.4,.1],0x426570);
for(const x of [-8,0,7.5]){box([x,1.12,-8],[2.5,2.2,1.1],0x406b72);box([x,2.3,-8],[2.6,.12,1.2],0xd8d8be);box([x,2.7,-8],[1.25,.7,.7],0x1c394a);box([x,2.72,-7.63],[.95,.43,.03],0x66a9b3,0,.35);for(let i=0;i<4;i++)box([x-.72+i*.48,.8,-7.43],[.37,1.25,.035],0x769d9b);}
cyl([-4.6,.9,2.6],[.46,.15,.46],0x6b8c88);for(let i=0;i<4;i++){const a=i*Math.PI/2;segment([-4.6+.2*Math.cos(a),.86,2.6+.2*Math.sin(a)],[-4.6+.35*Math.cos(a),.02,2.6+.35*Math.sin(a)],.04,0x49636c);}collecting=null;
}
furniture();
(function bakeStatics(){const groups=new Map(),raw={box:cubeData,sphere:sphereData,cyl:cylData};for(const o of statics){const key=o.hex+':'+o.emit;let g=groups.get(key);if(!g){g={hex:o.hex,emit:o.emit,vertices:[]};groups.set(key,g);}const m=o.m,src=raw[o.mesh];for(let i=0;i<src.length;i+=6){const p=src.slice(i,i+3),n=src.slice(i+3,i+6),q=[m[12],m[13],m[14]],nn=[0,0,0];for(let c=0;c<3;c++){const sq=m[c*4]**2+m[c*4+1]**2+m[c*4+2]**2||1;for(let r=0;r<3;r++){q[r]+=m[c*4+r]*p[c];nn[r]+=m[c*4+r]/sq*n[c];}}g.vertices.push(...q,...V.norm(nn));}}statics.length=0;let i=0;for(const g of groups.values()){const mesh='static'+i++;meshes[mesh]=makeMesh(g.vertices);statics.push({mesh,m:model([0,0,0]),hex:g.hex,emit:g.emit,alpha:1,pos:[0,0,0]});}})();
const Y=LabWorld.Y,defs=LabWorld.components();
const parts=Object.fromEntries(defs.map(c=>[c.id,c]));let wires=[],wireSerial=0,voltage=12,powered=false,switchClosed=false,mode='room',tool='move',pending=null,held=null,selected=null,records=[],solution,walkPhase=0,clock=0,sampleTimer=0,history=[],transition=0;
const EYE_HEIGHT=2.35;
const avatar={pos:[0,0,4.35],angle:Math.PI,path:[],done:null,moving:false};
// The camera origin always equals the player's eye position; yaw/pitch only rotate it.
const cam={yaw:0,pitch:-.16,fov:74*Math.PI/180,target:[0,2,0]},desired={yaw:0,pitch:-.16,fov:74*Math.PI/180};
let eye=[0,EYE_HEIGHT,4.35],forward=[0,0,-1],right=[1,0,0],viewUp=[0,1,0],vp,screenW=1,screenH=1,aspect=1,labels={},hitTargets=[],lastT=0,keys={},pointer=null,dragged=false,ghost=null,camDrag=false,toastTimer,aimed=null,aimText='';
const isLocked=()=>document.pointerLockElement===canvas;
function turn(dx,dy){desired.yaw+=dx*.0028;desired.pitch=clamp(desired.pitch-dy*.0028,-1.18,1.15);}
function releaseMouse(){if(isLocked())document.exitPointerLock?.();keys={};}
async function lockMouse(){canvas.focus({preventScroll:true});if(!canvas.requestPointerLock){toast('Оң батырманы басып сүйреңіз: жан-жағыңызға қарайсыз.');return;}try{await canvas.requestPointerLock();}catch(e){toast('Еркін тінтуір қолжетімсіз. Оң батырманы басып сүйреп қараңыз.');}}
function reach(c){return Math.hypot(c.pos[0]-avatar.pos[0],c.pos[2]-avatar.pos[2])<(c.placed?6.3:2.1);}
function interact(){if(net?.active&&gateVisible()){goGate(true);return;}if(held||tool!=='move'){handleClick(screenW/2,screenH/2);return;}const h=hit(screenW/2,screenH/2,'part');if(!h){toast('Нысананы құралға бағыттаңыз.');return;}const c=parts[h.id];if(!reach(c)){toast('Құралға жақындаңыз. WASD — жүру.');return;}if(!c.placed)pickup(c.id);else if(c.kind==='switch'){toggleSwitch();}else {selectPart(c.id);if(isLocked())toast(c.name+' таңдалды. R — қолға алу; Esc — кедергіні реттеу.');}}
const types={series:'Тізбектей қосылу',parallel:'Параллель қосылу',mixed:'Аралас қосылу',single:'Бір шам қосылған',open:'Тұйық контур жоқ',short:'Қысқа тұйықталу'};
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3100);}
function terminalName(id){return id==='Ba'?'Қорек +':id==='Bb'?'Қорек −':id.startsWith('K')?'K·'+(id.endsWith('a')?'1':'2'):id.slice(0,-1)+'·'+id.slice(-1);}
function termPos(id){const c=parts[id.slice(0,-1)];if(!c)return [0,0,0];const sign=id.endsWith('a')?-1:1;return V.add(c.pos,[sign*(c.kind==='battery'?.54:.43),c.kind==='battery'?.19:.16,c.kind==='battery'?.63:.3]);}
function label(id,txt,p,cls=''){let e=labels[id];if(!e){e=document.createElement('div');e.id='label-'+id;e.className='label3d '+cls;$('labels').append(e);labels[id]=e;}e.className='label3d '+cls;e.textContent=txt;const q=project(p);if(!q||q[0]<-60||q[0]>screenW+60||q[1]<-40||q[1]>screenH+40)e.style.display='none';else{e.style.display='';e.style.left=q[0]+'px';e.style.top=q[1]+'px';}e._used=true;return q;}
function project(p){const x=vp[0]*p[0]+vp[4]*p[1]+vp[8]*p[2]+vp[12],y=vp[1]*p[0]+vp[5]*p[1]+vp[9]*p[2]+vp[13],w=vp[3]*p[0]+vp[7]*p[1]+vp[11]*p[2]+vp[15];if(w<.1)return null;return [(x/w*.5+.5)*screenW,(-y/w*.5+.5)*screenH,w];}
function ray(x,y){const f=V.norm(V.sub(cam.target,eye)),r=V.norm(V.cross(f,[0,1,0])),u=V.cross(r,f),t=Math.tan(cam.fov/2);return {o:eye,d:V.norm(V.add(f,V.add(V.mul(r,(2*x/screenW-1)*aspect*t),V.mul(u,(1-2*y/screenH)*t))))};}
function planeAt(x,y,height){const r=ray(x,y),t=(height-r.o[1])/r.d[1];return t>0?V.add(r.o,V.mul(r.d,t)):null;}
function resize(){screenW=stage.clientWidth;screenH=stage.clientHeight;aspect=screenW/screenH;const dpr=Math.min(devicePixelRatio||1,1.7);canvas.width=Math.round(screenW*dpr);canvas.height=Math.round(screenH*dpr);gl.viewport(0,0,canvas.width,canvas.height);drawPlot();}new ResizeObserver(resize).observe(stage);
function component(c){const p=c.pos,at=(x,y,z)=>V.add(p,[x,y,z]),reading=solution?.lamps[c.id],bright=powered&&reading?clamp(reading.p/12,0,2):0;
if(c.kind==='battery'){box(at(0,.39,0),[1.45,.78,1.1],0xdce3d9);box(at(0,.4,.562),[1.32,.66,.035],0x294653);box(at(-.25,.55,.59),[.63,.28,.03],0x73c2b1,0,.5);cyl(at(.44,.49,.61),[.1,.07,.1],0x233b47);box(at(0,.77,0),[1.36,.045,1.02],0xc6d3c4);for(let i=0;i<6;i++)box(at(-.43+i*.17,.8,-.15),[.07,.015,.5],0x667d79);}
else if(c.kind==='lamp'){box(at(0,.055,0),[1.13,.11,.78],0xefe9d0);box(at(0,.12,-.02),[.55,.035,.5],0xd2c7a9);cyl(at(0,.22,-.05),[.23,.2,.23],0x657c7c);for(let y=.16;y<.32;y+=.04)cyl(at(0,y,-.05),[.239,.012,.239],0xc3c7ad);cyl(at(0,.38,-.05),[.135,.2,.135],0xc2c5ac);if(bright>0)sphere(at(0,.63,-.05),[.14,.19,.14],mixColor(0xa87535,0xffe598,Math.sqrt(clamp(bright,0,1))),1);sphere(at(0,.64,-.05),[.31,.37,.31],bright>0?0xffd789:0xc3e4de,bright>0?.8:.1,bright>0?.26:.22);segment(at(-.08,.5,-.035),at(.075,.68,-.035),.02,bright>0?0xfff0b5:0x8c8b72,bright>0?1:0);segment(at(.075,.68,-.035),at(-.025,.72,-.035),.02,bright>0?0xfff0b5:0x8c8b72,bright>0?1:0);if(!c.enabled)box(at(0,.93,-.05),[.2,.08,.05],0xb95445,0,.6);}
else if(c.kind==='resistor'){box(at(0,.07,0),[1.12,.14,.78],0xe8d7b8);box(at(0,.25,-.03),[.76,.26,.38],0x416070);for(let i=0;i<11;i++)segment(at(-.35+i*.065,.36,-.18),at(-.35+i*.065,.36,.12),.014,0xcead63);cyl(at((c.r-31.5)/70,.48,-.03),[.1,.17,.1],0x99cbb8);}
else if(c.kind==='ammeter'||c.kind==='voltmeter'){box(at(0,.22,0),[1.1,.44,.68],0xd7e1d3);box(at(0,.4,.07),[.82,.035,.39],0x203f4c);box(at(0,.423,.07),[.66,.018,.23],c.kind==='ammeter'?0x76d7b7:0x76bddd,0,.4);}
else if(c.kind==='motor'){box(at(0,.07,0),[1.12,.14,.78],0xd4d5bc);cyl(at(0,.34,-.05),[.28,.44,.28],0x607b83);segment(at(0,.53,-.05),at(0,.79,-.05),.045,0xd8c9aa);const turn=clock*(reading?.i||0)*7;box(at(0,.79,-.05),[.82,.035,.09],0x73cdbf,turn);box(at(0,.79,-.05),[.09,.035,.82],0x73cdbf,turn);}
else {box(at(0,.065,0),[1.1,.13,.68],0xdacba4);for(let x of [-.43,.43])cyl(at(x,.2,.18),[.095,.2,.095],0xbbab79);segment(at(-.43,.27,.18),at(.43,switchClosed?.27:.68,.18),.035,0xd3ac55);sphere(at(.43,switchClosed?.29:.7,.18),[.12,.09,.12],0x294c5d);}
for(const s of ['a','b']){const pos=termPos(c.id+s);cyl(pos,[.075,.08,.075],c.kind==='battery'?(s==='a'?0xc25e4b:0x346aaa):0xa89053);sphere(V.add(pos,[0,.06,0]),[.038,.035,.038],0xe5dab6);}
if(c.placed&&selected===c.id)ring(at(0,.008,0),.71,0x7bffe0);
}
function viewAt(x,y,z){return V.add(eye,V.add(V.mul(right,x),V.add(V.mul(viewUp,y),V.mul(forward,z))));}
function drawHands(){const sway=avatar.moving?Math.sin(walkPhase)*.012:0;
for(const side of [-1,1]){const wrist=held?viewAt(side*.26,-.36+sway,.9):viewAt(side*.43,-.31+sway,.9);const elbow=viewAt(side*.47,-.69+sway,.27);segment(elbow,wrist,.082,0xe8eee6);sphere(wrist,[.085,.07,.09],0x75b5af);const palm=V.add(wrist,V.mul(forward,.075));sphere(palm,[.082,.06,.1],0x99d2c7);for(let i=0;i<3;i++)sphere(V.add(palm,V.add(V.mul(right,(i-1)*.038),V.mul(forward,.07))),[.022,.036,.05],0x99d2c7);}
if(held)parts[held].pos=viewAt(0,-.51+sway,1.15);
}
function heldComponent(c){const start=frameObjects.length;component(c);const a=-cam.yaw,co=Math.cos(a),sn=Math.sin(a),scale=.54;
for(const o of frameObjects.slice(start)){const m=o.m;for(let col=0;col<3;col++){const x=m[col*4],z=m[col*4+2];m[col*4]=scale*(co*x+sn*z);m[col*4+1]*=scale;m[col*4+2]=scale*(-sn*x+co*z);}const d=V.sub(o.pos,c.pos),p=V.add(c.pos,[scale*(co*d[0]+sn*d[2]),scale*d[1],scale*(-sn*d[0]+co*d[2])]);m[12]=p[0];m[13]=p[1];m[14]=p[2];o.pos=p;}
}
function curve(w){const a=V.add(termPos(w.a),[0,.075,0]),b=V.add(termPos(w.b),[0,.075,0]),shift=.42+(w.id%4)*.12,c1=[a[0],Y+.11,a[2]+shift],c2=[b[0],Y+.11,b[2]+shift],pts=[];for(let i=0;i<=20;i++){const t=i/20,s=1-t;pts.push(a.map((v,k)=>s*s*s*v+3*s*s*t*c1[k]+3*s*t*t*c2[k]+t*t*t*b[k]));}return pts;}
function wireColor(w){return w.a==='Ba'||w.b==='Ba'?0xd9644c:w.a==='Bb'||w.b==='Bb'?0x3f74b8:0xd4a334;}
function drawWires(){for(const w of wires){const pts=curve(w);for(let i=1;i<pts.length;i++)segment(pts[i-1],pts[i],.022,wireColor(w));w.projected=pts.map(project);}if(pending){const pos=termPos(pending);sphere(V.add(pos,[0,.1,0]),[.11,.11,.11],0x6dffd6,1);}}
function updateLabels(){Object.values(labels).forEach(e=>e._used=false);hitTargets=[];
for(const c of defs){if(c.id===held||c.carrier)continue;const distance=Math.hypot(c.pos[0]-avatar.pos[0],c.pos[2]-avatar.pos[2]);
for(const height of [c.kind==='lamp'?.32:.3,c.kind==='lamp'?.68:.4]){const p=project(V.add(c.pos,[0,height,0]));if(p&&p[2]>.1)hitTargets.push({kind:'part',id:c.id,p,r:clamp(screenH/(2*Math.tan(cam.fov/2))*.3/p[2],19,75)});}
if(c.kind==='battery')label('supply',voltage+' V',V.add(c.pos,[-.2,.88,.2]));
else if(distance<8){const r=solution.lamps[c.id],t=c.name+(c.placed&&r?(c.kind==='ammeter'?' · '+fmt(r.i)+' A':c.kind==='voltmeter'?' · '+(r.floating?'—':fmt(r.u))+' В':c.kind==='resistor'?' · '+c.r+' Ом':c.kind==='lamp'?' · '+fmt(r.p,1)+' Вт':''):'');label('part'+c.id,t,V.add(c.pos,[0,c.kind==='lamp'?1.05:.82,0]),c.kind==='lamp'?'lampLabel':'');}
if(c.placed&&distance<6.4&&(mode==='bench'||tool==='wire'||tool==='erase'))for(const side of ['a','b']){const id=c.id+side,p=label('t'+id,c.id==='B'?(side==='a'?'+':'−'):c.id.replace('L','')+side,termPos(id),'term '+(c.id==='B'?(side==='a'?'positive':'negative'):'')+(pending===id?' chosen':''));if(p)hitTargets.push({kind:'terminal',id,p,r:20});}
}
label('board','ELECTRICITY  /  01',[2.5,3.75,-9.58]);Object.values(labels).forEach(e=>{if(!e._used)e.style.display='none';});
aimed=hit(screenW/2,screenH/2,tool==='wire'?'terminal':'part');const c=aimed&&parts[aimed.id.replace(/[ab]$/,'')];let text='';
if(avatar.path.length)text='Үстелдер арасымен жүріп келесіз · WASD — тоқтату';
else if(held)text=parts[held].name+' қолда · Үстелдің бос жеріне бағыттап, E басыңыз';
else if(tool==='wire')text=pending?terminalName(pending)+' → екінші клемма · E немесе сол батырма':'Клемманы нысанаға алыңыз · E немесе сол батырма';
else if(tool==='erase')text='Сымды нысанаға алып, E басыңыз';
else if(c)text=reach(c)?'E — '+(c.kind==='switch'&&c.placed?'кілтті ауыстыру':c.placed?c.name+' таңдау':c.name+' алу')+(c.placed&&c.kind==='lamp'?' · R — қолға алу':''):c.name+' · жақындаңыз';
else text=isLocked()?'WASD — жүру · B — үстел · Esc — мәзір':'Тінтуірді қосу · немесе оң батырманы басып сүйреу';
if(net?.active&&gateVisible())text=net.state?.goal.ok?'E — есікке дайынмын · екеуің бірге өтесіңдер':'Есік жабық · алдымен ортақ тапсырманы орындаңдар';if(text!==aimText){$('aimHint').textContent=text;aimText=text;}$('crosshair').classList.toggle('target',!!c&&reach(c));
}
function hit(x,y,kind){return hitTargets.filter(o=>(!kind||o.kind===kind)&&Math.hypot(o.p[0]-x,o.p[1]-y)<o.r).sort((a,b)=>(a.kind==='terminal'?-100:0)+(a.p[2]-b.p[2])-(b.kind==='terminal'?-100:0))[0]||null;}
function blocked(x,z){return LabWorld.blocked(x,z);}
// Small A* navigation grid keeps the character out of tables and walls.
function route(to,done){const step=.3,x0=-11.1,z0=-9,nx=75,nz=65,key=(x,z)=>x+','+z,pos=(x,z)=>[x0+x*step,0,z0+z*step];function nearest(p){let best=null,d=1e9;for(let x=0;x<nx;x++)for(let z=0;z<nz;z++){const q=pos(x,z);if(blocked(q[0],q[2]))continue;const dd=(q[0]-p[0])**2+(q[2]-p[2])**2;if(dd<d){d=dd;best=[x,z];}}return best;}const start=nearest(avatar.pos),end=nearest(to),endKey=key(...end),open=[start],g={[key(...start)]:0},came={},closed=new Set();let found=false;
while(open.length){open.sort((a,b)=>(g[key(...a)]+Math.abs(a[0]-end[0])+Math.abs(a[1]-end[1]))-(g[key(...b)]+Math.abs(b[0]-end[0])+Math.abs(b[1]-end[1])));const node=open.shift(),k=key(...node);if(closed.has(k))continue;closed.add(k);if(k===endKey){found=true;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const x=node[0]+dx,z=node[1]+dz,nk=key(x,z),p=pos(x,z);if(x<0||x>=nx||z<0||z>=nz||blocked(p[0],p[2])||closed.has(nk))continue;const cost=g[k]+1;if(g[nk]===undefined||cost<g[nk]){g[nk]=cost;came[nk]=k;open.push([x,z]);}}}
if(!found){toast('Бұл жерге жете алмадым. Бөлменің бос тұсына жылжыңыз.');return false;}const path=[];let k=endKey;while(k!==key(...start)){path.unshift(pos(...k.split(',').map(Number)));k=came[k];}avatar.path=path;avatar.done=done;if(!path.length){avatar.done=null;done?.();}return true;}
function setView(v,instant=false){mode=v;const b=v==='bench';if(b){desired.yaw=0;desired.pitch=-.22;desired.fov=70*Math.PI/180;}else desired.fov=74*Math.PI/180;if(instant){cam.yaw=desired.yaw;cam.pitch=desired.pitch;cam.fov=desired.fov;}for(const [id,on] of [['roomBtn',!b],['benchBtn',b]]){$(id).classList.toggle('active',on);$(id).setAttribute('aria-pressed',on);}updateHint();}
function bench(callback){if(Math.hypot(avatar.pos[0],avatar.pos[2]-4.2)<.45){setView('bench');callback?.();return;}toast('Жұмыс үстеліне жақындап келесіз…');route([0,0,4.2],()=>{setView('bench');callback?.();});}
function selectPart(id){selected=id;const c=parts[id];$('selection').hidden=!c||c.kind==='battery';if(!c||c.kind==='battery')return;$('selectedName').textContent=c.name;$('lampControls').hidden=!['lamp','resistor','motor'].includes(c.kind);if(['lamp','resistor','motor'].includes(c.kind)){$('resistance').value=c.r;$('resValue').textContent=c.r+' Ом';$('breakLamp').checked=!c.enabled;}updateHint();}
function pickup(id){const c=parts[id];if(net?.active){if(!c||c.id==='B')return;if(held){toast('Қолдағы құралды алдымен қойыңыз.');return;}if(c.carrier&&c.carrier!==net.playerId){toast('Бұл құрал серіктесіңіздің қолында.');return;}const take=()=>net.send('pickup',{id});if(c.placed){if(reach(c))take();else bench(take);}else{setView('room');toast(c.name+' алу үшін жақындап келесіз…');route([c.home[0]>0?4.2:-7.05,0,c.home[2]],take);}return;}if(!c||c.kind==='battery')return;if(held){toast('Алдымен қолдағы құралды үстелге қойыңыз.');return;}if(c.placed){wires=wires.filter(w=>!w.a.startsWith(id)&&!w.b.startsWith(id));c.placed=false;held=id;sound?.play('pickup');pending=null;setView('room');selectPart(null);recalc();updateTools();toast(c.name+' қолда. Үстелдегі бос жерге қайта қойыңыз.');return;}
setView('room');selected=null;$('selection').hidden=true;toast(c.name+' алу үшін сөреге бара жатыр…');route([c.home[0]>0?4.2:-7.05,0,c.home[2]],()=>{held=id;sound?.play('pickup');c.placed=false;avatar.angle=Math.PI/2;desired.yaw=Math.PI/2;desired.pitch=-.22;updateTools();recalc();toast(c.name+' қолда. «Үстелге қою» батырмасын басыңыз.');});}
function fits(id,pos){return pos[0]>=-3.08&&pos[0]<=3.08&&pos[2]>=-1.68&&pos[2]<=1.26&&!defs.some(c=>c.id!==id&&c.placed&&Math.abs(c.pos[0]-pos[0])<(c.kind==='battery'?1.4:1.22)&&Math.abs(c.pos[2]-pos[2])<.84);}
function emptySlot(id){const spots=[[-.55,Y,-.7],[1.12,Y,-.7],[2.8,Y,-.7],[-2.45,Y,.9],[-.65,Y,.9],[1.05,Y,.9],[2.75,Y,.9]];const preferred=spots.find(p=>fits(id,p));if(preferred)return preferred;for(const z of [-1.6,-.7,.18,1.1])for(let x=-3.06;x<=3.07;x+=.3){const p=[x,Y,z];if(fits(id,p))return p;}return null;}
function place(pos){if(!held)return;if(!pos)pos=emptySlot(held);if(!pos||!fits(held,pos)){toast('Үстелдің бос жерін таңдаңыз: құралдар бір-біріне тимеуі керек.');return;}if(net?.active){net.send('place',{x:pos[0],z:pos[2]});return;}sound?.play('place');const id=held,c=parts[id];c.pos=[pos[0],Y,pos[2]];c.placed=true;held=null;selectPart(id);tool='move';setTool('move');recalc();updateTools();toast(c.name+' орналастырылды. Енді «Сым» режимімен жалғаңыз.');}
function returnPart(){if(!selected)return;if(net?.active){net.send('return',{id:selected});return;}const c=parts[selected];wires=wires.filter(w=>!w.a.startsWith(c.id)&&!w.b.startsWith(c.id));c.placed=false;c.pos=[...c.home];if(held===c.id)held=null;selectPart(null);pending=null;recalc();updateTools();}
function addWire(a,b){if(net?.active){pending=null;updateHint();return net.send('connect',{a,b});}if(a===b){pending=null;toast('Әртүрлі екі клемманы таңдаңыз.');return false;}if(!parts[a.slice(0,-1)]?.placed||!parts[b.slice(0,-1)]?.placed)return false;if(wires.some(w=>(w.a===a&&w.b===b)||(w.a===b&&w.b===a))){toast('Бұл екі клемма жалғанған.');return false;}wires.push({a,b,id:++wireSerial});pending=null;sound?.play('connect');recalc();toast(terminalName(a)+' → '+terminalName(b)+' жалғанды');return true;}
function setTool(t){tool=t;pending=null;for(const [id,v] of [['moveTool','move'],['wireTool','wire'],['eraseTool','erase']]){$(id).classList.toggle('active',v===t);$(id).setAttribute('aria-pressed',v===t);}if(t!=='move'){selectPart(null);if(Math.hypot(avatar.pos[0],avatar.pos[2]+.2)<6)mode='bench';}updateHint();}
function updateHint(){const text=held?'Қолда: '+parts[held].name+' · E — нысанадағы бос жерге қою · B — үстелге бару':tool==='wire'?(pending?terminalName(pending)+' таңдалды · Екінші клемманы басыңыз · Q — болдырмау':'C · Сым: екі клемманы кезекпен басыңыз немесе нысанаға алып, E басыңыз'):tool==='erase'?'X · Өшіру: сымды басыңыз немесе нысанаға алып, E басыңыз':isLocked()?'WASD — жүру · E — әрекет · R — қолға алу · B — үстел · Esc — мәзір':'WASD — жүру · Оң батырмамен сүйреу — қарау · B — үстел';$('hint').textContent=text;canvas.style.cursor=isLocked()?'none':tool==='wire'?'crosshair':tool==='erase'?'not-allowed':held?'copy':'grab';}
function updateTools(){document.querySelectorAll('[data-pick]').forEach(b=>{const id=b.dataset.pick,c=parts[id];b.classList.toggle('active',held===id);b.querySelector('.state').textContent=held===id?'Қолда':c.placed?'Үстелде':'Алу';});$('placeBtn').hidden=!held;$('switchBtn').disabled=!parts.K.placed;$('switchBtn').textContent='Кілт: '+(switchClosed?'жабық':'ашық');updateHint();}
function recalc(){solution=CircuitEngine.solve(defs,wires,voltage,powered,switchClosed);$('voltageMetric').textContent=fmt(solution.u);$('currentMetric').textContent=fmt(solution.i);$('resMetric').textContent=fmt(solution.req);$('powerMetric').textContent=fmt(solution.power);$('voltageValue').textContent=voltage+' В';$('voltage').value=voltage;$('powerBtn').classList.toggle('on',powered);$('powerBtn').setAttribute('aria-pressed',powered);$('powerBtn').textContent=powered?'⏻ Қуат өшіру':'⏻ Қуат қосу';
const status=solution.short?'Қысқа тұйықталу! Қорғаныс шығысты ажыратты. Полюстерді тікелей жалғаған сымды өшіріңіз.':!solution.closed?(parts.K.placed&&!switchClosed?'Кілт ашық немесе контур толық емес. Жалғауларды тексеріңіз.':'Тізбек үзік. Қоректің + және − полюстерін шам арқылы қосыңыз.'):!powered?'Тізбек дайын. Жарықты жағу үшін қуатты қосыңыз.':'Тізбек тұйық · '+types[solution.type].toLowerCase();$('status').textContent=status;$('status').className='status '+(solution.short?'error':solution.closed&&powered?'ok':'');
$('lampReadings').innerHTML=defs.filter(c=>c.kind==='lamp').map(c=>{const r=solution.lamps[c.id];return '<tr><td><span class="lampDot" style="background:'+(r.p>.01?'#ffce75':'#63777b')+'"></span>'+c.id+(!c.placed?(c.carrier?' · қолда':' · сөреде'):!c.enabled?' · үзік':'')+'</td><td>'+(c.placed?fmt(r.u):'—')+'</td><td>'+(c.placed?fmt(r.i):'—')+'</td><td>'+(c.placed?fmt(r.p):'—')+'</td></tr>';}).join('');
$('instrumentReadings').innerHTML=defs.filter(c=>['resistor','ammeter','voltmeter','motor'].includes(c.kind)).map(c=>{const r=solution.lamps[c.id],valid=c.placed&&!r.floating;return '<tr><td>'+c.name+'</td><td>'+(valid?fmt(r.u):'—')+'</td><td>'+(valid?fmt(r.i,c.kind==='ammeter'?3:2):'—')+'</td></tr>';}).join('');
$('typeLabel').textContent=types[solution.type];let f=solution.type==='series'?'R = R₁ + R₂ + …\nI₁ = I₂ = I · U = U₁ + U₂ + …':solution.type==='parallel'?'1/R = 1/R₁ + 1/R₂ + …\nU₁ = U₂ = U · I = I₁ + I₂ + …':solution.type==='mixed'?'Түйінде: Σ Iкір = Σ Iшығ\nӘр шамда: I = U / R; P = UI':solution.type==='short'?'R = 0 Ом · қорғаныс іске қосылды\nИдеал қысқа тұйықталудың шексіз тогы көрсетілмейді.':'I = U / R   ·   P = UI';if(solution.closed)f+='\nI = '+fmt(solution.u)+' / '+fmt(solution.req)+' = '+fmt(solution.i)+' А';else if(!solution.short)f+='\nТұйық жол жоқ: I = 0 А.';$('formulaText').textContent=f;
$('wireCount').textContent=wires.length;$('wires').innerHTML=wires.map(w=>'<div class="wireRow"><span>'+terminalName(w.a)+' ↔ '+terminalName(w.b)+'</span><button data-remove-wire="'+w.id+'" aria-label="'+terminalName(w.a)+' және '+terminalName(w.b)+' арасындағы сымды өшіру">×</button></div>').join('');
const options=defs.filter(c=>c.placed).flatMap(c=>[c.id+'a',c.id+'b']).map(id=>'<option value="'+id+'">'+terminalName(id)+'</option>').join('');for(const id of ['fromTerminal','toTerminal']){const old=$(id).value;$(id).innerHTML=options;if([...$(id).options].some(o=>o.value===old))$(id).value=old;}if($('fromTerminal').value===$('toTerminal').value&&$('toTerminal').options.length>1)$('toTerminal').selectedIndex=1;
let count=defs.filter(c=>c.kind==='lamp'&&c.placed).length;const steps=[count>=2,wires.length>=3,solution.closed&&powered&&!solution.short,records.length>=2];steps.forEach((ok,i)=>$('step'+(i+1)).classList.toggle('done',ok));$('missionTitle').textContent=solution.closed&&powered?'Өлше де, салыстыр':'Жарықты өзің жақ';$('missionText').textContent=solution.closed&&powered?'Бір шамды үзіп көр. Қалған шамға не болады? Өлшеуді журналға жаз.':held?'Құрал қолыңда. Үстелге қойып, келесі құралды ал.':count>=2?'Сым режимінде клеммаларды жалға. Кілтті жауып, қуатты қос.':'Екі шамды сөреден ал. Үстелге қойып, тұйық тізбек құрастыр.';updateTools();sound?.power(powered&&!solution.short);net?.refresh();}
function preset(type){if(net?.active){toast('Бірлескен миссияда тізбекті өздерің құрастырыңдар.');return;}avatar.path=[];avatar.done=null;held=null;selected=null;pending=null;wires=[];wireSerial=0;powered=true;switchClosed=true;voltage=12;defs.forEach(c=>{if(c.kind==='lamp'){c.r=12;c.enabled=true;c.placed=false;c.pos=[...c.home];}});parts.B.pos=[-2.5,Y,-.65];parts.K.placed=true;parts.K.pos=[-1.8,Y,.91];parts.L1.placed=true;parts.L1.pos=[-.55,Y,-.7];parts.L2.placed=true;parts.L2.pos=[1.15,Y,-.7];const pairs=type==='series'?[['Ba','Ka'],['Kb','L1a'],['L1b','L2a'],['L2b','Bb']]:type==='parallel'?[['Ba','Ka'],['Kb','L1a'],['Kb','L2a'],['L1b','Bb'],['L2b','Bb']]:[['Ba','Ka'],['Kb','L1a'],['L1b','L2a'],['L1b','L3a'],['L2b','Bb'],['L3b','Bb']];if(type==='mixed'){parts.L3.placed=true;parts.L3.pos=[1.15,Y,.91];}pairs.forEach(([a,b])=>wires.push({a,b,id:++wireSerial}));avatar.pos=[0,0,4.2];avatar.angle=Math.PI;setView('bench');setTool('move');selectPart(null);recalc();toast(types[type]+': құралдар мен сымдарды еркін өзгерте аласыз.');}
function togglePower(){if(net?.active){net.send('power');return;}powered=!powered;sound?.play('power');recalc();}
function toggleSwitch(){if(net?.active){net.send('switch');return;}if(parts.K.placed){switchClosed=!switchClosed;sound?.play('switch');recalc();}}
function clearCircuit(){if(net?.active){net.send('clear');return;}wires=[];pending=null;powered=false;recalc();toast('Сымдар алынды.');}
function removeWire(id){if(net?.active){net.send('removeWire',{id});return;}wires=wires.filter(w=>w.id!==id);recalc();}
function changeVoltage(value){if(net?.active){net.send('voltage',{value});return;}voltage=value;recalc();}
function changeResistance(value){if(!parts[selected]||!['lamp','resistor','motor'].includes(parts[selected].kind))return;if(net?.active){net.send('resistance',{id:selected,value});return;}parts[selected].r=value;$('resValue').textContent=value+' Ом';recalc();}
function breakSelected(enabled){if(!parts[selected]||!['lamp','resistor','motor'].includes(parts[selected].kind))return;if(net?.active){net.send('break',{id:selected,enabled});return;}parts[selected].enabled=enabled;recalc();}
function drawPlot(){const c=$('plot'),w=c.clientWidth||300,h=99,d=Math.min(devicePixelRatio||1,2);if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d);}const x=c.getContext('2d');if(!x)return;x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);const max=Math.max(1,...history.map(o=>o.i))*1.15,left=32,right=w-8,top=7,bottom=77;x.font='10px "Segoe UI", Arial';x.textAlign='right';x.fillStyle='#a8bbc6';x.strokeStyle='#304854';x.lineWidth=1;for(let j=0;j<=2;j++){let y=bottom-(bottom-top)*j/2;x.beginPath();x.moveTo(left,y);x.lineTo(right,y);x.stroke();x.fillText(fmt(max*j/2,1),left-5,y+3);}x.textAlign='left';x.fillText('−20 с',left,94);x.textAlign='right';x.fillText('қазір',right,94);if(!history.length)return;x.beginPath();history.forEach((o,i)=>{const px=right-(clock-o.t)/20*(right-left),py=bottom-o.i/max*(bottom-top);if(i===0)x.moveTo(px,py);else x.lineTo(px,py);});x.strokeStyle='#7bf0d4';x.lineWidth=2;x.stroke();const last=history.at(-1);x.beginPath();x.arc(right-(clock-last.t)/20*(right-left),bottom-last.i/max*(bottom-top),3,0,Math.PI*2);x.fillStyle='#a1f6e1';x.fill();}
function record(){const r={t:new Date().toLocaleTimeString('kk-KZ'),voltage,sourceOn:powered,switchClosed,type:solution.type,short:solution.short,closed:solution.closed,u:solution.u,i:solution.i,req:solution.req,power:solution.power,lamps:JSON.parse(JSON.stringify(solution.lamps)),resistors:defs.filter(c=>['lamp','resistor','ammeter','voltmeter','motor'].includes(c.kind)).map(c=>({id:c.id,r:c.kind==='voltmeter'?Infinity:c.r,placed:c.placed,enabled:c.enabled!==false})),wires:wires.map(w=>[w.a,w.b])};records.push(r);$('recordCount').textContent=records.length;recalc();toast('№'+records.length+' өлшеу журналға жазылды.');}
function renderJournal(){$('journalRows').innerHTML=records.map((r,i)=>'<tr><td>'+(i+1)+'</td><td>'+types[r.type]+(!r.sourceOn?' · қуат өшірулі':'')+'</td><td>'+fmt(r.u)+'</td><td>'+fmt(r.i)+'</td><td>'+fmt(r.req)+'</td><td>'+fmt(r.power)+'</td></tr>').join('');$('journalInfo').textContent=records.length?records.length+' өлшеу жазылды. CSV файлына шамдар мен қосымша құралдардың U, I, P және R мәндері де енгізіледі.':'Журнал бос. Тізбекті құрып, «Өлшеуді жазу» батырмасын басыңыз.';$('downloadBtn').disabled=!records.length;$('deleteRecordsBtn').disabled=!records.length;
const s=records.find(r=>r.type==='series'&&r.sourceOn&&r.closed);const p=records.find(r=>r.type==='parallel'&&r.sourceOn&&r.closed&&s&&r.u===s.u&&JSON.stringify(r.resistors)===JSON.stringify(s.resistors));$('comparison').textContent=s&&p?'Бірдей '+fmt(s.u,0)+' В кернеуде параллель тізбектің жалпы тогы тізбектей тізбектен '+fmt(p.i/s.i)+' есе үлкен болды. Қуаттарын және әр шамның жарықтығын салыстырыңыз.':'Әділ салыстыру үшін бірдей кернеу, бірдей шамдар және бірдей кедергілермен екі қосылуды өлшеңіз.';}
function download(){const header=['№','Уақыт','Қосылу','Қуат қосулы','Кілт жабық','Қойылған U (В)','Шығыс U (В)','I (А)','R (Ом)','P (Вт)',...['L1','L2','L3','R1','A','V','M'].flatMap(id=>[id+' үстелде',id+' бүтін',id+' R (Ом)',id+' U (В)',id+' I (А)',id+' P (Вт)']),'Сымдар'];const rows=records.map((r,i)=>[i+1,r.t,types[r.type],r.sourceOn,r.switchClosed,r.voltage,r.u,r.i,Number.isFinite(r.req)?r.req:'Infinity',r.power,...r.resistors.flatMap(c=>[c.placed,c.enabled,c.r,r.lamps[c.id].floating?'':r.lamps[c.id].u,r.lamps[c.id].floating?'':r.lamps[c.id].i,r.lamps[c.id].p]),r.wires.map(w=>w.join('↔')).join(' | ')]);const quote=v=>'"'+String(v).replace(/"/g,'""')+'"';const csv='\uFEFF'+[header,...rows].map(r=>r.map(quote).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'})),a=document.createElement('a');a.href=url;a.download='Elektr_Lab_olsheuler.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
// Pointer interaction uses projected terminal handles and a camera ray / tabletop plane.
function eventXY(e){const r=canvas.getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top];}
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==2)return;if(isLocked()){if(e.button===0)handleClick(screenW/2,screenH/2);return;}const [x,y]=eventXY(e);pointer={x,y,lastX:x,lastY:y,id:e.pointerId,hit:hit(x,y),origin:null};dragged=false;camDrag=e.button===2||e.altKey||(e.pointerType==='touch'&&!pointer.hit);canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true});if(tool==='move'&&!held&&!camDrag){const h=hit(x,y,'part');if(h&&parts[h.id].placed&&h.id!=='B'){pointer.hit=h;pointer.origin=[...parts[h.id].pos];selectPart(h.id);}}});
canvas.addEventListener('pointermove',e=>{if(isLocked())return;const [x,y]=eventXY(e);if(held){const p=planeAt(x,y,Y);ghost=p&&fits(held,p)?p:null;}if(!pointer)return;const dx=x-pointer.lastX,dy=y-pointer.lastY;if(Math.hypot(x-pointer.x,y-pointer.y)>5)dragged=true;if(camDrag||(dragged&&!pointer.hit&&tool==='move')){turn(dx*1.8,dy*1.8);camDrag=true;}else if(dragged&&pointer.origin&&tool==='move'){const p=planeAt(x,y,Y);if(p&&fits(pointer.hit.id,p))parts[pointer.hit.id].pos=[p[0],Y,p[2]];}pointer.lastX=x;pointer.lastY=y;});
function onRelease(e){if(!pointer||isLocked())return;if(dragged&&pointer.origin&&net?.active){const c=parts[pointer.hit.id],dest=[...c.pos];c.pos=pointer.origin;net.send('move',{id:c.id,x:dest[0],z:dest[2]});}const [x,y]=eventXY(e);if(!dragged&&!camDrag)handleClick(x,y);pointer=null;camDrag=false;ghost=null;}
canvas.addEventListener('pointerup',onRelease);canvas.addEventListener('pointercancel',()=>{pointer=null;camDrag=false;ghost=null;});
canvas.addEventListener('wheel',e=>{e.preventDefault();desired.fov=clamp(desired.fov+e.deltaY*.0008,55*Math.PI/180,88*Math.PI/180);},{passive:false});
document.addEventListener('mousemove',e=>{if(isLocked())turn(e.movementX||0,e.movementY||0);});
document.addEventListener('pointerlockchange',()=>{keys={};pointer=null;camDrag=false;stage.classList.toggle('locked',isLocked());$('lookBtn').textContent=isLocked()?'Esc · Мәзір':'▶ Тінтуірді қосу';$('lookBtn').setAttribute('aria-pressed',isLocked());if(!isLocked())cancelPath();updateHint();});
document.addEventListener('pointerlockerror',()=>toast('Оң батырманы басып сүйреңіз немесе экрандағы бағыттауыштарды қолданыңыз.'));
function handleClick(x,y){if(net?.active&&hit(x,y,'gate')){goGate(true);return;}if(held){const p=planeAt(x,y,Y);if(p&&Math.hypot(p[0]-avatar.pos[0],p[2]-avatar.pos[2])<6.3)place(p);else toast('Үстелдің бос жеріне қараңыз. B — үстелге бару.');return;}if(tool==='wire'){const h=hit(x,y,'terminal');if(!h){pending=null;updateHint();return;}if(!pending){pending=h.id;toast(terminalName(h.id)+' таңдалды. Екінші клемманы басыңыз.');}else addWire(pending,h.id);updateHint();return;}if(tool==='erase'){let best=null,d=16;for(const w of wires)for(let i=1;i<(w.projected||[]).length;i++){const a=w.projected[i-1],b=w.projected[i];if(!a||!b)continue;const vx=b[0]-a[0],vy=b[1]-a[1],t=clamp(((x-a[0])*vx+(y-a[1])*vy)/(vx*vx+vy*vy||1),0,1),dd=Math.hypot(x-a[0]-t*vx,y-a[1]-t*vy);if(dd<d){d=dd;best=w;}}if(best){removeWire(best.id);toast('Сым өшірілді.');}else toast('Сымды дәл басыңыз немесе «Сымдар» тізімін ашыңыз.');return;}const h=hit(x,y,'part');if(h){const c=parts[h.id];if(!c.placed)pickup(c.id);else {selectPart(c.id);if(isLocked()&&c.kind==='lamp')toast(c.name+' таңдалды · R — қолға алу · Esc — баптау');}}else selectPart(null);}
function bind(id,fn){$(id).addEventListener('click',fn);}bind('roomBtn',()=>{setView('room');canvas.focus({preventScroll:true});});bind('lookBtn',()=>{if(isLocked())releaseMouse();else lockMouse();});bind('interactBtn',interact);bind('lookUp',()=>desired.pitch=clamp(desired.pitch+.15,-1.18,1.15));bind('lookDown',()=>desired.pitch=clamp(desired.pitch-.15,-1.18,1.15));bind('benchBtn',()=>bench());bind('moveTool',()=>setTool('move'));bind('wireTool',()=>setTool('wire'));bind('eraseTool',()=>setTool('erase'));bind('placeBtn',()=>bench(()=>place()));bind('pickupBtn',()=>pickup(selected));bind('returnBtn',returnPart);bind('powerBtn',togglePower);bind('switchBtn',toggleSwitch);bind('presetBtn',()=>preset($('preset').value));bind('clearBtn',clearCircuit);bind('connectBtn',()=>addWire($('fromTerminal').value,$('toTerminal').value));bind('recordBtn',record);bind('downloadBtn',download);bind('deleteRecordsBtn',()=>{if(confirm('Журналдағы барлық өлшеуді өшіру керек пе?')){records=[];$('recordCount').textContent=0;renderJournal();recalc();}});bind('helpBtn',()=>{releaseMouse();cancelPath();$('help').showModal();});bind('journalBtn',()=>{releaseMouse();cancelPath();renderJournal();$('journal').showModal();});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));bind('fullBtn',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){toast('Толық экранды браузер мәзірінен қосуға болады.');}});bind('missionToggle',()=>{$('missionText').hidden=!$('missionText').hidden;$('missionToggle').textContent=$('missionText').hidden?'+':'−';});bind('zoomIn',()=>desired.fov=clamp(desired.fov-.08,55*Math.PI/180,88*Math.PI/180));bind('zoomOut',()=>desired.fov=clamp(desired.fov+.08,55*Math.PI/180,88*Math.PI/180));bind('rotateLeft',()=>desired.yaw-=.23);bind('rotateRight',()=>desired.yaw+=.23);
$('voltage').addEventListener('change',e=>changeVoltage(+e.target.value));$('voltage').addEventListener('input',e=>{$('voltageValue').textContent=e.target.value+' В';if(!net?.active)changeVoltage(+e.target.value);});$('resistance').addEventListener('change',e=>changeResistance(+e.target.value));$('resistance').addEventListener('input',e=>{$('resValue').textContent=e.target.value+' Ом';if(!net?.active)changeResistance(+e.target.value);});$('breakLamp').addEventListener('change',e=>breakSelected(!e.target.checked));document.querySelectorAll('[data-pick]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.pick;if(parts[id].placed)bench(()=>selectPart(id));else pickup(id);}));$('wires').addEventListener('click',e=>{const b=e.target.closest('[data-remove-wire]');if(b)removeWire(+b.dataset.removeWire);});
function cancelPath(){avatar.path=[];avatar.done=null;}
const keyMap={ArrowUp:'w',ArrowDown:'s',ArrowLeft:'a',ArrowRight:'d',KeyW:'w',KeyS:'s',KeyA:'a',KeyD:'d'};
window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||(e.target.tagName==='BUTTON'&&['Space','Enter'].includes(e.code)))return;const move=keyMap[e.code];if(move){e.preventDefault();keys[move]=true;cancelPath();if(mode==='bench')setView('room');return;}if(e.repeat)return;if(e.code==='Space'){e.preventDefault();togglePower();}else if(e.code==='KeyB')bench();else if(e.code==='KeyC')setTool('wire');else if(e.code==='KeyX')setTool('erase');else if(e.code==='KeyQ')setTool('move');else if(e.code==='Escape'){releaseMouse();pending=null;cancelPath();updateHint();}else if(e.code==='KeyE'){e.preventDefault();interact();}else if(e.code==='KeyR'){const h=hit(screenW/2,screenH/2,'part'),c=h&&parts[h.id];if(c&&c.id!=='B'&&reach(c))pickup(c.id);else toast('Алғыңыз келген құралды нысанаға алыңыз.');}else if(e.code==='KeyF')lockMouse();});
window.addEventListener('keyup',e=>{if(keyMap[e.code])keys[keyMap[e.code]]=false;});window.addEventListener('blur',()=>{keys={};});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys={};cancelPath();}});
document.querySelectorAll('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();keys[b.dataset.move]=true;cancelPath();setView('room');b.setPointerCapture(e.pointerId);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>{keys[b.dataset.move]=false;});});
function moveAvatar(dt){let dx=0,dz=0;avatar.moving=false;const speed=3.15;const sx=clamp((keys.d?1:0)-(keys.a?1:0)+(window.LabInput?.x||0),-1,1),sz=clamp((keys.s?1:0)-(keys.w?1:0)+(window.LabInput?.y||0),-1,1);if(sx||sz){const angle=cam.yaw,normal=Math.max(1,Math.hypot(sx,sz));dx=(sx*Math.cos(angle)-sz*Math.sin(angle))/normal*dt*speed;dz=(sx*Math.sin(angle)+sz*Math.cos(angle))/normal*dt*speed;}
else if(avatar.path.length){const p=avatar.path[0],v=[p[0]-avatar.pos[0],0,p[2]-avatar.pos[2]],d=V.len(v);if(d<.06){avatar.path.shift();if(!avatar.path.length){const cb=avatar.done;avatar.done=null;cb?.();}return;}dx=v[0]/d*Math.min(d,speed*dt);dz=v[2]/d*Math.min(d,speed*dt);desired.yaw=Math.atan2(v[0],-v[2]);desired.pitch=-.13;}
if(dx||dz){const old=[...avatar.pos];if(!blocked(avatar.pos[0]+dx,avatar.pos[2]))avatar.pos[0]+=dx;if(!blocked(avatar.pos[0],avatar.pos[2]+dz))avatar.pos[2]+=dz;avatar.moving=Math.hypot(avatar.pos[0]-old[0],avatar.pos[2]-old[2])>.0001;if(avatar.moving){avatar.angle=Math.atan2(dx,dz);walkPhase+=dt*11;}}}
function frame(t){const dt=Math.min((t-lastT)/1000||.016,.05);lastT=t;clock+=dt;if(!$('lobby')||$('lobby').hidden)moveAvatar(dt);else avatar.moving=false;if(avatar.moving&&clock-lastFootstep>.45){lastFootstep=clock;sound?.play('step');}const k=Math.min(1,dt*14);const delta=Math.atan2(Math.sin(desired.yaw-cam.yaw),Math.cos(desired.yaw-cam.yaw));cam.yaw+=delta*k;cam.pitch+=(desired.pitch-cam.pitch)*k;cam.fov+=(desired.fov-cam.fov)*k;
eye=[avatar.pos[0],EYE_HEIGHT,avatar.pos[2]];forward=[Math.sin(cam.yaw)*Math.cos(cam.pitch),Math.sin(cam.pitch),-Math.cos(cam.yaw)*Math.cos(cam.pitch)];right=V.norm(V.cross(forward,[0,1,0]));viewUp=V.cross(right,forward);cam.target=V.add(eye,forward);
vp=mulMat(perspective(cam.fov,aspect,.045,45),lookAt(eye,cam.target));gl.clearColor(.63,.75,.77,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(U.VP,false,vp);gl.uniform3fv(U.Eye,eye);gl.uniform3fv(U['Lamps[0]'],defs.filter(c=>c.kind==='lamp').flatMap(c=>V.add(c.pos,[0,.66,0])));gl.uniform3fv(U.Glow,defs.filter(c=>c.kind==='lamp').map(c=>clamp(solution.lamps[c.id].p/12,0,2)));
frameObjects=[];drawGate(dt);drawHands();defs.forEach(c=>{if(c.id===held)heldComponent(c);else if(!c.carrier)component(c);});drawPeers(dt);drawWires();if(held&&isLocked()){const p=planeAt(screenW/2,screenH/2,Y);ghost=p&&fits(held,p)?p:null;}if(ghost&&held)ring([ghost[0],Y+.01,ghost[2]],.68,0x7bffe0);
transparent=[];for(const o of [...statics,...frameObjects]){if(o.alpha<1)transparent.push(o);else draw(o);}transparent.sort((a,b)=>V.len(V.sub(eye,b.pos))-V.len(V.sub(eye,a.pos)));gl.depthMask(false);transparent.forEach(draw);gl.depthMask(true);updateLabels();gateLabel();if(net?.active)net.pose({pos:[...avatar.pos],yaw:cam.yaw,pitch:cam.pitch});sampleTimer+=dt;if(sampleTimer>.25){sampleTimer=0;history.push({t:clock,i:solution.i});history=history.filter(o=>clock-o.t<=20);drawPlot();}requestAnimationFrame(frame);}
function takeAim(){const h=hit(screenW/2,screenH/2,'part'),c=h&&parts[h.id];if(c&&c.id!=='B'&&reach(c))pickup(c.id);else toast('Құралды нысанаға алыңыз.');}
function gateVisible(){const p=project([0,1.65,10.7]);return !!p&&Math.hypot(p[0]-screenW/2,p[1]-screenH/2)<120&&Math.hypot(avatar.pos[0],avatar.pos[2]-9.3)<3;}
function goGate(near=false){if(!net?.active){toast('Бөлмелерге бірге өту үшін QR сессиясына кіріңіз.');return;}if(!net.state?.goal.ok){toast('Алдымен ортақ тапсырманы орындаңдар.');return;}if(held){toast('Алдымен қолдағы құралды қойыңыз.');return;}if(near&&Math.hypot(avatar.pos[0],avatar.pos[2]-9.3)<2.3){net.ready();return;}releaseMouse();route([net.playerId==='p1'?-.6:.6,0,9.3],()=>{desired.yaw=Math.PI;desired.pitch=-.06;net.ready();});}
function drawGate(dt){const accent=[0x7bead3,0x9aacff,0xffcf83][net?.state?.stage||0];for(const x of [-9,9])box([x,4.25,-9.84],[3.7,.15,.08],accent,0,.8);const open=!!net?.state?.goal.ok;doorOpen+=(Number(open)-doorOpen)*Math.min(1,dt*3);const c=open?0x66e5ab:0xdeb264;box([-1.55,1.65,10.8],[.16,3.3,.3],0x254a5b);box([1.55,1.65,10.8],[.16,3.3,.3],0x254a5b);box([0,3.31,10.8],[3.25,.16,.3],c,0,.65);for(const side of [-1,1]){box([side*(.75+doorOpen*1.25),1.6,10.8],[1.46,3.2,.1],0x426b74);box([side*(.75+doorOpen*1.25),1.95,10.72],[1.02,1.2,.025],0x8eb6bc);box([side*.14,1.42,10.57],[.055,.32,.08],c,0,.5);}}
function gateLabel(){label('roomStage',net?.active?net.state?.goal.title:'ЭЛЕКТР LAB · ЖЕКЕ ЖАТТЫҒУ',[2.5,4.5,-9.65]);const text=net?.state?.finished?'МИССИЯ ОРЫНДАЛДЫ':net?.state?.goal.ok?'ЕСІК АШЫҚ · ЕКЕУІҢ БІРГЕ ӨТІҢДЕР':'КЕЛЕСІ БӨЛМЕ · ТАПСЫРМАНЫ ОРЫНДА';const p=label('exit',text,[0,3.65,10.65]);const target=project([0,1.65,10.7]);if(p&&target)hitTargets.push({kind:'gate',id:'gate',p:target,r:75});for(const peer of peers)if(peer.present)label('peer'+peer.id,peer.name,[(peer.view||peer.pos)[0],2.62,(peer.view||peer.pos)[2]]);}
function drawPeers(dt){for(const peer of peers){if(!peer.present)continue;peer.view=peer.view||[...peer.pos];peer.view=peer.view.map((v,i)=>v+(peer.pos[i]-v)*Math.min(1,dt*12));const p=peer.view,a=peer.yaw+Math.PI,at=(x,y,z)=>[p[0]+Math.cos(a)*x+Math.sin(a)*z,y,p[2]-Math.sin(a)*x+Math.cos(a)*z];const col=peer.id==='p1'?0x82d4b5:0xa99cde;
box(at(0,1.37,0),[.58,.91,.36],0xe1e9de,a);box(at(0,1.62,.2),[.2,.18,.035],col,a);sphere(at(0,2.05,0),[.23,.28,.22],0xd3ad90);sphere(at(0,2.2,-.02),[.235,.15,.22],0x304650);box(at(0,2.06,.21),[.38,.11,.03],0x86c8c6,a);for(const side of [-1,1]){segment(at(side*.17,.94,0),at(side*.18,.13,0),.115,0x355568);box(at(side*.18,.09,.07),[.22,.17,.35],0x273f4b,a);segment(at(side*.34,1.73,0),at(side*.37,1.13,peer.held?.48:0),.085,0xe5eddd);sphere(at(side*.37,1.13,peer.held?.48:0),[.085,.09,.085],col);}if(peer.held){const c=parts[peer.held];if(c){c.pos=at(0,1.13,.62);const savedYaw=cam.yaw;cam.yaw=-a;heldComponent(c);cam.yaw=savedYaw;}}label('peer'+peer.id,peer.name,[p[0],2.62,p[2]]);}}
function applyShared(s,id,fresh){const me=s.players.find(p=>p.id===id);if(!me)return;for(const remote of s.parts){const c=parts[remote.id];if(c){c.carrier=null;Object.assign(c,JSON.parse(JSON.stringify(remote)));}}wires=s.wires.map(w=>({...w}));wireSerial=Math.max(0,...wires.map(w=>w.id));voltage=s.voltage;powered=s.powered;switchClosed=s.switchClosed;held=me.held;updatePeers(s.players,id);if(fresh){avatar.pos=[...me.pos];cancelPath();keys={};pending=null;selected=null;desired.yaw=me.yaw;desired.pitch=me.pitch;mode='room';if(s.stage>0){$('roomTransition').textContent=LabWorld.STAGES[s.stage].title;$('roomTransition').hidden=false;setTimeout(()=>$('roomTransition').hidden=true,2200);}$('selection').hidden=true;}recalc();if(selected)selectPart(selected);}
function updatePeers(players,id){const old=new Map(peers.map(p=>[p.id,p]));peers=players.filter(p=>p.id!==id).map(p=>({...p,view:old.get(p.id)?.view||[...p.pos]}));}
net?.attach({apply:applyShared,peers:updatePeers,correct(pos){avatar.pos=[...pos];cancelPath();},toast,release:releaseMouse,short:()=>!!solution?.short});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('fatal').hidden=false;$('fatalText').textContent='Графика уақытша тоқтады. Файлды қайта ашып көріңіз.';});
// Read-only diagnostics and interaction hooks used for verification.
window.ElectricLab={interact,takeAim,bench,gate:goGate,cancelWalk:cancelPath,getState:()=>({components:JSON.parse(JSON.stringify(defs)),wires:wires.map(({a,b,id})=>({a,b,id})),voltage,powered,switchClosed,mode,tool,held,selected,solution,records:records.length,camera:{eye:[...eye],yaw:cam.yaw,pitch:cam.pitch,fov:cam.fov,firstPerson:true},locked:isLocked(),avatar:{pos:[...avatar.pos],pathLength:avatar.path.length}}),preset,connect:addWire,select:selectPart,pickup,place,setView,setTool,recalculate:recalc,project,termPos,engine:CircuitEngine};
recalc();resize();requestAnimationFrame(frame);
})();
